### ISSUE TITLE
请教一下Vue2 + Vuepress 1的实现思路

### ISSUE THREAD

**Issue by HuiWang111** [bfehub/vmi#14]
![vmi](https://github.com/bfehub/vmi/assets/40290843/e0553858-4dfc-427f-b7a0-5dc3b35c2761)
我看了一下源码，大致整理了一下渲染 demo 的逻辑，想要在 Vuepress 1中实现一下，但是发现 Vuepress 1 中 extendPageData 传过来的 page 对象没有 sfcBlocks 属性，没法将 demo 注册为页面可以使用的组件；我想了各种办法去实现，最后都行不通；我第一次写 Vuepress 插件还不太熟悉，想请教一下 Vuepress 1的实现思路，万分感谢！

**Comment by haiweilian** [comment]
前面的都没问题，v1中没这些用于额外设置的属性。

但我觉得只要能 md 文件内容后拼上脚本就可以吧。就像可以直接写和动态补上的没区别，https://vuepress.vuejs.org/zh/guide/using-vue.html#脚本和样式提升。

**Comment by HuiWang111** [comment]
> 前面的都没问题，v1中没这些用于额外设置的属性。
> 
> 但我觉得只要能 md 文件内容后拼上脚本就可以吧。就像可以直接写和动态补上的没区别，[https://vuepress.vuejs.org/zh/guide/using-vue.html#脚本和样式提升。](https://vuepress.vuejs.org/zh/guide/using-vue.html#%E8%84%9A%E6%9C%AC%E5%92%8C%E6%A0%B7%E5%BC%8F%E6%8F%90%E5%8D%87%E3%80%82)

动态导入我试了，绝对路径和相对路径都提示无法找到模块，绝对路径像 E:\... 这样的肯定是不行；相对路径的话不知道应该相对于哪个位置（我写相对于 Previewer 组件的路径不行）

**Comment by haiweilian** [comment]
那不对啊，假如你先在 md 文件中写死绝对路径导入要展示的组件是不可以的吗？

**Comment by HuiWang111** [comment]
> 那不对啊，假如你先在 md 文件中写死绝对路径导入要展示的组件是不可以的吗？

这个我倒没试过，我待会试一下

**Comment by HuiWang111** [comment]
> 那不对啊，假如你先在 md 文件中写死绝对路径导入要展示的组件是不可以的吗？

不对呀，在 md  文件中使用组件需要将组件放到 .vuepress/components 目录下，在 md 文件中注册组件是不行的吧

**Comment by haiweilian** [comment]
确定可以直接导入的， vue 2.7 后可以 setup 简化导入。 

![image](https://github.com/bfehub/vmi/assets/34850199/ea98835d-cba4-43d8-9627-06ccfd874b59)

自动补充上这段脚本，v1 中没办在 extendPageData 动态更改内容。可以试试自定义 markdown 的渲染函数， args 中有足够的源信息区分渲染的哪个文件。

![image](https://github.com/bfehub/vmi/assets/34850199/8fc86d4f-1186-42c8-826a-fba3a3eee7ab)

**Comment by HuiWang111** [comment]
原来还可以这样！！！困扰我很久的问题解决了！你简直是我的神，哈哈哈哈。
