### ISSUE TITLE
请教一下Vue2 + Vuepress 1的实现思路（2）

### ISSUE THREAD

**Issue by HuiWang111** [bfehub/vmi#15]
之前的方法在 md 文件中写死的情况下确实是可行的，但是在实时分析 <demo> 标签并渲染组件的情况下不太可行。

逻辑大致是这样：在 html_inline 函数中解析 <demo> 并渲染 demo 和 demo 源码，同时往 store 里存 demo 的组件名称和路径；然后在 render 中添加 <script setup> 注册 demo 组件。

但问题在于 render 函数是先于 html_inline 函数执行的，因此并不能正确的拿到 store 的组件名称和路径。

我想了很多方法始终解决不了这个问题，麻烦解答一下，万分感谢！！！

**Comment by haiweilian** [comment]
一点点想法，提前运行一次 render 用于收集信息。

- 在 render 中先手动 render.call 一次，你的自定义规则会执行，这次的渲染只是为了收集组件的信息。最后还是返回 render.call 交给 vuepress 去调用。

- 那么由于渲染了两次，所以你的自定义规则也会执行两次。这时可以设计一个临时变量作为是否收集组件信息的开关。

- 不知道 vuepress 内置的解析渲染两次会不会有问题，万一有问题可以把 args 的信息深拷贝一下让两次环境隔离。

```js
md.render = (...args) => {
      // 默认渲染一次用于收集依赖信息
      isRun = true;
      render.call(md, ...args);
      isRun = false;

      return render.call(md, ...args);
};
```

**Comment by HuiWang111** [comment]
好的，我回头试一下，感谢！！！

**Comment by HuiWang111** [comment]
已经实现了。

分了两个 store 存数据。一个是 `组件名称/组件路径` store，用于生成 import 语句；一个是 `<demo>标签源码/渲染后的代码` ，因为这个方案每次会执行两次 html_inline, 第二次就直接从 store 中取；

万分感谢！！！
