### ISSUE TITLE
怎样支持 raw 和 iframe 属性共同使用？

### ISSUE THREAD

**Issue by hawtim** [bfehub/vmi#7]
iframe 模式下，src 引用的 vue 文件如果有 import 的话会解析，导致报错，但是使用 raw 只能展示代码

![image](https://user-images.githubusercontent.com/11072796/223675633-f9e4da9d-ef87-4da4-b75a-7bca869805b7.png)

**Comment by haiweilian** [comment]
我想你应该需要给 vuepress 的 vite 配置别名的，不然解析不了的。
https://v2.vuepress.vuejs.org/zh/reference/bundler/vite.html#%E9%85%8D%E7%BD%AE%E9%A1%B9

**Comment by hawtim** [comment]
嗯嗯，这个我暂时用别名解决了。

我在想能不能支持既支持 raw 又支持 iframe，那样有些代码块我这边是从项目中同步过来的，对应会有一些项目的 import，如果要解析就会很麻烦。

**Comment by haiweilian** [comment]
哦哦明白了，是说使用 demoUrl 外部链接的时候。代码只用做展示没有实际效果是吧。(其实也就是没什么用，这个可以改)

**Comment by haiweilian** [comment]
Releases #13
