### ISSUE TITLE
use codeBlockPlugin will block vuepress build with createVueApp is not a function

### ISSUE THREAD

**Issue by hawtim** [bfehub/vmi#8]
用了这个插件打包 vuepress 的时候会触发 createVueApp 错误

![image](https://user-images.githubusercontent.com/11072796/223704825-fd35ce24-156d-4955-9fc8-7f254d4a2165.png)

![image](https://user-images.githubusercontent.com/11072796/223704663-ca979005-5544-41fa-b509-5a6b407a3260.png)

**Comment by haiweilian** [comment]
这看着不像插件代码的错呀，使用的版本都是多少。

**Comment by hawtim** [comment]
研究了很久，把 vmi 这边的代码拷贝到我的工程里，构建也是同样的报错，但是在 vmi 项目下 vuepress 的构建就是正常的。
两边的 vuepress 的依赖是一样的。

**Comment by hawtim** [comment]
![image](https://user-images.githubusercontent.com/11072796/223727759-1caf5911-943c-44e9-b94e-b39169ee70c9.png)

**Comment by haiweilian** [comment]
复现了，明天调试下。

**Comment by hawtim** [comment]
> 复现了，明天调试下。

正想整个复现demo给你…

**Comment by haiweilian** [comment]
发布在 #10

**Comment by hawtim** [comment]
感谢～
