### ISSUE TITLE
demoUrl 属性不支持动态组装属性，会渲染成 -iframe.html

### ISSUE THREAD

**Issue by hawtim** [bfehub/vmi#9]
markdown 源码

<img width="780" alt="image" src="https://user-images.githubusercontent.com/11072796/223908003-7e139280-507a-4249-ad5e-7081627aaff5.png">

实际渲染的结果

<img width="479" alt="image" src="https://user-images.githubusercontent.com/11072796/223908266-08cb0d2a-49fe-4aa3-bbc9-f44c1d3e57a3.png">

**Comment by haiweilian** [comment]
<demo> 只是一个标签，通过  posthtml 解析属性无法解析运行时变量。

**Comment by hawtim** [comment]
目前我的一个解决方案是在插件的 config 里传入一个选项，比如 demoBase，如果 demoUrl 不是 https? 开头的就统一加上。

![image](https://user-images.githubusercontent.com/11072796/223941215-bb23a945-6be6-40b1-9e15-618e5fcf414b.png)



另外一个是通过在 markdown 里写 html 的方式，因为没有注册这个 demo 组件，解析不出来。
看能不能类似 npmBadge 提供一个组件，把这个组件注册一下就可以解析了

```html
<script setup>
import { ref, computed, watch } from 'vue';
const runtimeBase = RUNTIME_BASE;
const basicURL = `${runtimeBase}/#/sform/basic`;
</script>
<div>
  <demo src="../demos/sformbasic.vue" iframe="275" :demoUrl="basicURL"></demo>
</div> 
```

**Comment by haiweilian** [comment]
1. 全局配置可以实现简单方便。
2. demo 标签在内部会替换成一个组件的，只不过属性没有接收(解析完应该是 ":demoUrl")，可以传过去解析下。如何解析的规则都在 [parseVue](https://github.com/bfehub/vmi/blob/main/packages/plugin-code-block/src/node/parse/parseVue.ts) 一个文件里。

你可以实现这些功能不，当然加的功能都可以提上来，有什么问题可以问我。等下我把打包错误的发下版。

**Comment by hawtim** [comment]
嗯，我找个时间提上来。
